[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# this patch is taken from NotJustYet
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if G.GAME.chips - G.GAME.blind.chips >= 0 or G.GAME.current_round.hands_left < 1 then"
position = "at"
payload = '''
if (G.GAME.chips - G.GAME.blind.chips >= 0 and not GLOBAL_twow_grace_period) or G.GAME.current_round.hands_left < 1 then
	stop_use()
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if #G.hand.cards < 1 and #G.deck.cards < 1 and #G.play.cards < 1 then"
position = "at"
payload = '''
if false then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.SPEEDFACTOR = (G.STAGE == G.STAGES.RUN and not G.SETTINGS.paused and not G.screenwipe) and self.SETTINGS.GAMESPEED or 1"
position = "at"
payload = '''
self.SPEEDFACTOR = (G.STAGE == G.STAGES.RUN and not G.SETTINGS.paused and not G.screenwipe) and self.SETTINGS.GAMESPEED or 1
if next(SMODS.find_card('j_twow_speediness_potion')) then
	for _, joker in ipairs(SMODS.find_card('j_twow_speediness_potion')) do
		self.SPEEDFACTOR = self.SPEEDFACTOR * (joker.ability.extra.new_game_speed or 1)
	end
end
'''
match_indent = true

        
